import * as fs from "fs";
import * as path from "path";
import type { ProcessedSkillRecord } from "../lib/types.js";
import { readProcessedData } from "../lib/fs-utils.js";

const OUTPUT_PATH = path.join(process.cwd(), "src", "data", "skills-batch-clawhub.ts");

function escapeString(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

function formatSkillEntry(record: ProcessedSkillRecord): string {
  const lines: string[] = [];
  lines.push("  {");
  lines.push(`    slug: "${escapeString(record.slug)}",`);
  lines.push(`    name: "${escapeString(record.name)}",`);
  lines.push(`    category: "${record.category}",`);

  if (record.subcategory) {
    lines.push(`    subcategory: "${escapeString(record.subcategory)}",`);
  }

  lines.push(`    description: "${escapeString(record.description || "")}",`);

  if (record.clawhub_url) {
    lines.push(`    source_url: "${escapeString(record.clawhub_url)}",`);
  }

  if (record.skill_url && record.skill_url_confidence >= 0.5) {
    lines.push(`    skill_url: "${escapeString(record.skill_url)}",`);
  }

  lines.push(`    source: "clawhub",`);
  lines.push(`    verified: ${record.tier === "verified"},`);
  lines.push(`    framework: "ClawHub",`);

  const tags = record.extracted_tags?.slice(0, 10) || record.tags?.slice(0, 10) || [];
  if (tags.length > 0) {
    lines.push(`    tags: [${tags.map((t) => `"${escapeString(t)}"`).join(", ")}],`);
  } else {
    lines.push(`    tags: [],`);
  }

  lines.push("  },");
  return lines.join("\n");
}

export async function generateBatchFile(
  records: ProcessedSkillRecord[]
): Promise<string> {
  const newSkills = records.filter((r) => r.dedupe.action === "new");

  if (newSkills.length === 0) {
    console.log("[GenerateBatch] No new skills to generate");
    return OUTPUT_PATH;
  }

  const byCategory = newSkills.reduce(
    (acc, r) => {
      acc[r.category] = (acc[r.category] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  const categoryList = Object.entries(byCategory)
    .map(([c, n]) => `${c}: ${n}`)
    .join(", ");

  const fileContent = `import type { Skill } from "@/data/skills";

/**
 * ClawHub Skills Batch
 * Auto-generated by the ClawHub ingestion pipeline
 * Total: ${newSkills.length} skills
 * Categories: ${categoryList}
 * Generated: ${new Date().toISOString()}
 */
export const CLAWHUB_SKILLS: Skill[] = [
${newSkills.map(formatSkillEntry).join("\n")}
];
`;

  fs.writeFileSync(OUTPUT_PATH, fileContent);
  console.log(`[GenerateBatch] Wrote ${newSkills.length} skills to ${OUTPUT_PATH}`);

  return OUTPUT_PATH;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const processed = readProcessedData<ProcessedSkillRecord[]>("processed-records.json");
  if (!processed) {
    console.error("No processed records found");
    process.exit(1);
  }
  generateBatchFile(processed)
    .then((path) => console.log(`Generated: ${path}`))
    .catch((err) => {
      console.error("Failed:", err);
      process.exit(1);
    });
}
