import type { SecurityRule } from "../types";

export const credentialHarvestRules: SecurityRule[] = [
  {
    id: "CRED-001",
    category: "credential_harvesting",
    severity: "critical",
    description: "Hardcoded AWS access key",
    pattern: /AKIA[0-9A-Z]{16}/g,
  },
  {
    id: "CRED-002",
    category: "credential_harvesting",
    severity: "critical",
    description: "AWS secret access key pattern",
    pattern: /(?:aws_secret_access_key|AWS_SECRET_ACCESS_KEY)\s*[=:]\s*['"]?[A-Za-z0-9/+=]{40}['"]?/gi,
  },
  {
    id: "CRED-003",
    category: "credential_harvesting",
    severity: "high",
    description: "SSH private key header",
    pattern: /-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH|PGP)\s+PRIVATE\s+KEY-----/g,
  },
  {
    id: "CRED-004",
    category: "credential_harvesting",
    severity: "critical",
    description: "OpenAI API key pattern",
    pattern: /sk-[a-zA-Z0-9]{20,}/g,
  },
  {
    id: "CRED-005",
    category: "credential_harvesting",
    severity: "critical",
    description: "Anthropic API key pattern",
    pattern: /sk-ant-[a-zA-Z0-9-]{20,}/g,
  },
  {
    id: "CRED-006",
    category: "credential_harvesting",
    severity: "critical",
    description: "Stripe API key pattern",
    pattern: /(?:sk|pk)_(?:test|live)_[a-zA-Z0-9]{24,}/g,
  },
  {
    id: "CRED-007",
    category: "credential_harvesting",
    severity: "high",
    description: "GitHub personal access token",
    pattern: /ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{22,}/g,
  },
  {
    id: "CRED-008",
    category: "credential_harvesting",
    severity: "high",
    description: "Generic API key assignment",
    pattern: /(?:api[_-]?key|apikey|api[_-]?secret)\s*[=:]\s*['"][a-zA-Z0-9_-]{20,}['"]/gi,
  },
  {
    id: "CRED-009",
    category: "credential_harvesting",
    severity: "high",
    description: "Keychain/credential store access (macOS)",
    pattern: /security\s+find-(?:generic|internet)-password/gi,
  },
  {
    id: "CRED-010",
    category: "credential_harvesting",
    severity: "low",
    description: "Environment variable access",
    pattern: /process\.env\[|os\.environ\[|os\.getenv\(|System\.getenv\(/gi,
  },
  {
    id: "CRED-011",
    category: "credential_harvesting",
    severity: "medium",
    description: "Bulk environment variable dump",
    pattern: /Object\.keys\s*\(\s*process\.env\s*\)|dict\s*\(\s*os\.environ\s*\)|environ\.items\(\)/gi,
  },
  {
    id: "CRED-012",
    category: "credential_harvesting",
    severity: "high",
    description: "Hardcoded password assignment",
    pattern: /(?:password|passwd|pwd)\s*[=:]\s*['"][^'"]{8,}['"]/gi,
  },
  {
    id: "CRED-013",
    category: "credential_harvesting",
    severity: "critical",
    description: "Google Cloud service account key",
    pattern: /"type"\s*:\s*"service_account"[^}]*"private_key"/g,
  },
  {
    id: "CRED-014",
    category: "credential_harvesting",
    severity: "high",
    description: "Slack token pattern",
    pattern: /xox[baprs]-[0-9]{10,}-[a-zA-Z0-9-]+/g,
  },
  {
    id: "CRED-015",
    category: "credential_harvesting",
    severity: "high",
    description: "Discord bot token pattern",
    pattern: /[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{27}/g,
  },
];
